kind: Deployment
apiVersion: apps/v1
metadata:
  name: rvstore-ui-deployment
  labels:
    app: rvstore-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rvstore-ui
  template:
    metadata:
      labels:
        app: rvstore-ui
    spec:
      containers:
      - name: rvstore-ui
        image: vergeops/k8s-rvstore-ui:1.0
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-ui
spec:
  selector:  
    app: rvstore-ui
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort  
